name: CD - Deploy to EC2

on:
    workflow_run:
        workflows: ["CI - Build and Push"]
        types:
            - completed

jobs:
    Copy-script-and-run-on-ec2:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Create directory on EC2
              run: sudo mkdir -p /home/${{ secrets.EC2_USER }}/Demo-project
              
            - name: Copy script to EC2
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  source: "scripts/install-docker.sh"
                  target: "/home/${{ secrets.EC2_USER }}/Demo-project/"

            - name: Run script on EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                    cd /home/${{ secrets.EC2_USER }}/Demo-project/scripts
                    chmod +x /home/${{ secrets.EC2_USER }}/Demo-project/scripts/install-docker.sh
                    ./install-docker.sh

    deploy-to-ec2:
        needs: Copy-script-and-run-on-ec2
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Deploy docker container to EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                    docker rm -f portfolio || true     #remove old container if exists
                    docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio:latest   #pull latest image from docker hub
                    docker run -d \    #run container in detached mode
                      --name portfolio \
                      -p 80:80 \
                      ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
                      docker system prune -f    #clean up unused docker resources
                    
    store-to-s3:
        needs: deploy-to-ec2
        runs-on: ubuntu-latest
        steps:
            - name: checkout source code
              uses: actions/checkout@v4

            - name: configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: deploy files to S3
              run: |
                aws s3 sync . s3://${{ secrets.S3_BUCKET }} \
                --delete \
                --exclude ".git/*" \
                --exclude ".github/*"
